### ISSUE TITLE
java 11 dependency problems

### ISSUE THREAD

**Issue by stepodev** [authzforce/restful-pdp#4]
Following the "Getting Started" section fails with OpenJDK-11. OpenJDK-8 is working fine.
System: Ubuntu 18.04, Debian testing.  fails.  works. 

```
Reason:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:621)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at org.ow2.authzforce.rest.pdp.cxf.springboot.CxfJaxrsPdpSpringBootApp.main(CxfJaxrsPdpSpringBootApp.java:50)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 9 more
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:621)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
```

Running 'mvn package' fails with:

```
-------------------------------------------------------
Running org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.206 sec <<< FAILURE! - in org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest
initialize(org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest)  Time elapsed: 0.119 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.startServer(XacmlRestProfileJaxRsTest.java:65)
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.initialize(XacmlRestProfileJaxRsTest.java:86)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.startServer(XacmlRestProfileJaxRsTest.java:65)
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.initialize(XacmlRestProfileJaxRsTest.java:86)


Results :

Failed tests: 
  XacmlRestProfileJaxRsTest.initialize:86->startServer:65 NoClassDefFound javax/...

```
Which might be the problem addressed [here](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j).

Adding to the pom.xml of jaxrs:
```
<!-- Java 6 = JAX-B Version 2.0   -->
		<!-- Java 7 = JAX-B Version 2.2.3 -->
		<!-- Java 8 = JAX-B Version 2.2.8 -->
		<dependency>
		    <groupId>javax.xml.bind</groupId>
		    <artifactId>jaxb-api</artifactId>
		    <version>2.2.11</version>
		</dependency>
		<dependency>
		    <groupId>com.sun.xml.bind</groupId>
		    <artifactId>jaxb-core</artifactId>
		    <version>2.2.11</version>
		</dependency>
		<dependency>
		    <groupId>com.sun.xml.bind</groupId>
		    <artifactId>jaxb-impl</artifactId>
		    <version>2.2.11</version>
		</dependency>
		<dependency>
	        <groupId>javax.activation</groupId>
	        	<artifactId>activation</artifactId>
	        <version>1.1.1</version>
        </dependency>
```
leads to `mvn package` failing with 

```
[INFO] Building org.ow2.authzforce:authzforce-ce-restful-pdp-jaxrs 1.3.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for com.sun.xml.bind:jaxb-impl:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] 
[INFO] --- license-maven-plugin:3.0:format (format-sources-license) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Updating license headers...
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/stepo/workspace/restful-pdp/jaxrs/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- license-maven-plugin:3.0:format (format-test-sources-license) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Updating license headers...
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ authzforce-ce-restful-pdp-jaxrs ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ authzforce-ce-restful-pdp-jaxrs ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/home/stepo/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.899 sec <<< FAILURE! - in org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest
initialize(org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest)  Time elapsed: 0.84 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceFeature
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.startServer(XacmlRestProfileJaxRsTest.java:74)
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.initialize(XacmlRestProfileJaxRsTest.java:86)
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.WebServiceFeature
	at
org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.startServer(XacmlRestProfileJaxRsTest.java:74)
	at org.ow2.authzforce.rest.pdp.jaxrs.test.XacmlRestProfileJaxRsTest.initialize(XacmlRestProfileJaxRsTest.java:86)
```

At which point I'm stuck. I'm guessing resolving `[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details` is the next step?

**Comment by cdanger** [comment]
I am surprised you mention OpenJDK 11 since it is not released yet, to my knowledge. Are you sure it is not rather OpenJDK 10?  We don't support versions later than 8 officially at the moment.

Anyway, it looks like a missing dependency again. Indeed, most Java EE releated modules - including most javax.xml.* packages - have been removed from the JRE since OpenJDK 9. So you have to add the missing packages on your own, like you did for the first issue. So as far as I understand, for OpenJDK 10, you need to add:

```xml
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.0</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>javax.activation-api</artifactId>
    <version>1.2.0</version>
</dependency>
```

For the last issue, after looking at some blog on java 9 migration, you also need to add this one but in scope *test* only (it is only used for the unit tests):

```xml
<dependency>
    <groupId>javax.xml.ws</groupId>
    <artifactId>jaxws-api</artifactId>
    <version>2.3.0</version>
    <scope>test</scope>
</dependency>
```

I haven't tested it, so please let me know how it goes. Besides, if you find a way to handle different sets of dependencies according to the target JDK version in Maven (one for jdk 8 and one for jdk >= 9), maybe with Maven profiles, you can make a pull request, so that we can fix it once and for all for everybody.  Thanks :-)

**Comment by cdanger** [comment]
No feedback from OP for 24 days, considering this solved.

**Comment by AlexOzol** [comment]
Hi! I have the same problem: OpenJDK-11, same maven output. 

>so please let me know how it goes

Your solution helps me. Thanks!
